name: Send Teams notification

on: [workflow_dispatch]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   
        
      - name: Run Python script
        id: message 
        run: |
          output=$(python ./extracts_status.py)
          echo "script_output=$output" >> $GITHUB_OUTPUT
          echo $output
      
      - name: Send Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '{'@type': 'MessageCard', '@context': 'http://schema.org/extensions', 'themeColor': 'F35E5E', 'summary': 'Docker Test - Github build 9.2.1.13:FAILED', 'sections': [{'activityTitle': 'Docker Test - Github build 9.2.1.13:FAILED', 'activitySubtitle': '2023-03-31 11:17:28 - 2023-03-31 11:18:28', 'activityImage': './red.png', 'facts': [{'name': 'Description', 'value': 'Neoload POC Docker'}]}, {'title': 'SLA', 'facts': [{'name': {'TRANSACTION:NeoloaPOC_TransactionExample'}, 'value': {'FAILED'}}, {'name': {'REQUEST:Jmetertest'}, 'value': {'PASSED'}}, {'name': {'TRANSACTION:NeoloaPOC_TransactionExample'}, 'value': {'PASSED'}}]}]}' $TEAMS_WEBHOOK_URL
