name: Send Teams notification

on: 
  workflow_dispatch:
    inputs:
      test_name: 
        description: 'name'
        required: true
        type: string
        default: 'service'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   
      
      - name: "Set up webhook"
        run: |
          if [ "${{ inputs.test_name }}" = "service" ]; then
            webhook_id="111"
          else
            if [ "${{ inputs.test_name }}" = "test"  ]; then
              webhook_id="222"
            else
              webhook_id="333"
            fi
          fi
          echo "webhook_id=$webhook_id" >> $GITHUB_ENV
          
      - name: "Print"
        run: echo ${{ env.webhook_id }}
