name: Send Teams notification

on: [workflow_dispatch]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Run Python script
        run: |
          output=$(python - <<EOF
            import re
            fname = "./report_dc3078d8-ee29-4411-b4ef-fa0f0f0203f2.html"
            print((re.search("Status: (.*?)<", open(fname, 'r', encoding='utf-8').read()).group(1))
          EOF)
          echo "::set-output name=script_output::$output"
