name: Send Teams notification

on: [workflow_dispatch]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   
        
      - name: Run Python script
        run: |
          output=$(python ./extracts_status.py)
          echo "script_output=$output" >> $GITHUB_OUTPUT
          echo $output
      
      - name: Send Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '$output' $TEAMS_WEBHOOK_URL
