name: Send Teams notification

on: [workflow_dispatch]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run Python script
        run: |
          output=$(python - <<EOF
          import re
          fname = "report_dc3078d8-ee29-4411-b4ef-fa0f0f0203f2.html"
          print(open(fname, 'r', encoding='utf-8').read())
          EOF)
          echo "::set-output name=script_output::$output"
      - name: Send Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '{
            "@context": "http://schema.org/extensions",
            "@type": "MessageCard",
            "themeColor": "0072C6",
            "title": "GitHub Action workflow completed",
            "text": "Your GitHub Action workflow has completed."
          }' $TEAMS_WEBHOOK_URL
