name: Send Teams notification

on: 
  workflow_dispatch:
    inputs:
      test_name: 
        description: 'name'
        required: true
        type: string
        default: 'service'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   
      
      - name: "Set up webhook"
        run: |
          if [ "${{ inputs.test_name }}" = "service" ]; then
            export webhook_id="7bb78fb627534affb6bae68b60da825b"
          else
            export webhook_id="7a6b9a6798224773adce577dff2f98f7"
          fi
        env:
          TEAMS_WEBHOOK_URL: ${{ env.webhook_id }}
          
      - name: "Print"
        run: echo $TEAMS_WEBHOOK_URL
